### ISSUE TITLE
plain text

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/meteor-serverSideLogin#1]
@benwiley It would be great if this required some level of encryption for the sending client. I don't love accepting plain text passwords if we can help it. https://www.npmjs.com/package/bcrypt is a pretty amazing library for encoding and decoding. I'd rather require it be encoded then we decode it on our end.

Thoughts?

**Comment by benwiley** [comment]
@jbaxleyiii I understand the concern but don't know the best answer.  In a traditional login form, passwords are sent clear-text from client to server and security is up to SSL.  That is the approach I was going with.  If we hash the password some way on the client before sending to the server, the hash essentially becomes the password, as an attacker would simply need to intercept the hash and use it to login.  Again, SSL is the security here.  The most secure way to do this is probably with private and public keys.  I'm researching this more, but let me know if there is a certain way you prefer I go.

**Comment by jbaxleyiii** [comment]
@benwiley you are totally right! I like the public and private key / token method if we can go that way but you are right about SSL!
